from tkinter import *
root= Tk()
root.geometry("1800x800")

button1=Button(root,text="Open File")
button1.place(relx=0.0,rely=0.0)
button2=Button(root,text="Save File")
button2.place(relx=0.05,rely=0.0)
button3=Button(root,text="Change to black and white")
button3.place(relx=0.85,rely=0.1)
button4=Button(root,text="Select area to crop")
button4.place(relx=0.8,rely=0.2)
button5=Button(root,text="Apply crop")
button5.place(relx=0.9,rely=0.2)
button6=Button(root,text="Flip Horizontally")
button6.place(relx=0.8,rely=0.3)
button7=Button(root,text="Flip vertically")
button7.place(relx=0.9,rely=0.3)
button8=Button(root,text="Rotate left")
button8.place(relx=0.8,rely=0.4)
button9=Button(root,text="Rotate right")
button9.place(relx=0.9,rely=0.4)
button10=Button(root,text="Apply Saturation")
button10.place(relx=0.9,rely=0.5)
button11=Button(root,text="Apply Sharpness")
button11.place(relx=0.9,rely=0.55)
button12=Button(root,text="Apply Exposure")
button12.place(relx=0.9,rely=0.6)
button13=Button(root,text="Apply Contrast")
button13.place(relx=0.9,rely=0.65)
button14=Button(root,text="Highlight Border")
button14.place(relx=0.85,rely=0.7)
button15=Button(root,text="Insert Text")
button15.place(relx=0.8,rely=0.85)
button16=Button(root,text="Fix Position")
button16.place(relx=0.9,rely=0.85)
label=Label(root)
label.place(relx=0.9,rely=0.8)
scale1=Scale(root, from_=1, to=50,orient=HORIZONTAL)
scale1.place(relx=0.8,rely=0.5)
scale2=Scale(root, from_=1, to=50,orient=HORIZONTAL)
scale2.place(relx=0.8,rely=0.55)
scale3=Scale(root, from_=1, to=50,orient=HORIZONTAL)
scale3.place(relx=0.8,rely=0.6)
scale4=Scale(root, from_=1, to=50,orient=HORIZONTAL)
scale4.place(relx=0.8,rely=0.65)
root.mainloop()
